### ISSUE TITLE
WET4 mod / skin cleanup

### ISSUE THREAD

**Issue by Phanoix** [tbs-sct/gcconnex#174]
This will be split into several sub-issues due to the sheer size of the mod and the amount of work it would take to not only clean up but to split up up into logical skin and non-skin parts.
- [x] #175  -  wet4 skin cleanup - Split skin parts from the rest
- [x] #176  -  wet4 skin cleanup - remove unneeded files
- [ ] #177  -  wet4 skin cleanup - update function and file headers to match our new format
